In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("C:/Users/DELL/Projects/cascade-cup-22/train.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450000 entries, 0 to 449999
Data columns (total 20 columns):
 #   Column                Non-Null Count   Dtype  
---  ------                --------------   -----  
 0   order_time            450000 non-null  object 
 1   order_id              450000 non-null  int64  
 2   order_date            450000 non-null  object 
 3   allot_time            450000 non-null  object 
 4   accept_time           449843 non-null  object 
 5   pickup_time           447579 non-null  object 
 6   delivered_time        444782 non-null  object 
 7   rider_id              450000 non-null  int64  
 8   first_mile_distance   450000 non-null  float64
 9   last_mile_distance    450000 non-null  float64
 10  alloted_orders        433052 non-null  float64
 11  delivered_orders      432659 non-null  float64
 12  cancelled             450000 non-null  int64  
 13  undelivered_orders    432659 non-null  float64
 14  lifetime_order_count  449947 non-null  float64
 15  

In [4]:
df.isnull().sum()

order_time                   0
order_id                     0
order_date                   0
allot_time                   0
accept_time                157
pickup_time               2421
delivered_time            5218
rider_id                     0
first_mile_distance          0
last_mile_distance           0
alloted_orders           16948
delivered_orders         17341
cancelled                    0
undelivered_orders       17341
lifetime_order_count        53
reassignment_method     436256
reassignment_reason     436247
reassigned_order        436247
session_time              3675
cancelled_time          444782
dtype: int64

In [5]:
df=df.drop(['reassignment_method','reassignment_reason','reassigned_order','cancelled_time'],axis=1)

In [6]:
df['order_time'] = pd.to_datetime(df.order_time, format='%d-%m-%Y %H:%M')
df['hour']=df['order_time'].dt.hour

In [7]:
df=df.drop(['order_time','order_id','order_date','allot_time','pickup_time','delivered_time','rider_id'],axis=1)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450000 entries, 0 to 449999
Data columns (total 10 columns):
 #   Column                Non-Null Count   Dtype  
---  ------                --------------   -----  
 0   accept_time           449843 non-null  object 
 1   first_mile_distance   450000 non-null  float64
 2   last_mile_distance    450000 non-null  float64
 3   alloted_orders        433052 non-null  float64
 4   delivered_orders      432659 non-null  float64
 5   cancelled             450000 non-null  int64  
 6   undelivered_orders    432659 non-null  float64
 7   lifetime_order_count  449947 non-null  float64
 8   session_time          446325 non-null  float64
 9   hour                  450000 non-null  int64  
dtypes: float64(7), int64(2), object(1)
memory usage: 34.3+ MB


In [9]:
df.drop(['accept_time'],axis=1,inplace=True);

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450000 entries, 0 to 449999
Data columns (total 9 columns):
 #   Column                Non-Null Count   Dtype  
---  ------                --------------   -----  
 0   first_mile_distance   450000 non-null  float64
 1   last_mile_distance    450000 non-null  float64
 2   alloted_orders        433052 non-null  float64
 3   delivered_orders      432659 non-null  float64
 4   cancelled             450000 non-null  int64  
 5   undelivered_orders    432659 non-null  float64
 6   lifetime_order_count  449947 non-null  float64
 7   session_time          446325 non-null  float64
 8   hour                  450000 non-null  int64  
dtypes: float64(7), int64(2)
memory usage: 30.9 MB


In [11]:
df['hour']=df['hour'].astype('category')
df['cancelled']=df['cancelled'].astype('category')


In [12]:
Y=df.cancelled

In [13]:
X=df.drop(['cancelled'],axis=1)

In [14]:
X_dum=pd.get_dummies(X,prefix_sep='-',drop_first=True)

In [15]:
X_dum

first_mile_distance  last_mile_distance  alloted_orders  \
0                    1.5666                2.65            46.0   
1                    2.5207                2.76             8.0   
2                    2.2074                4.80             1.0   
3                    2.1894                6.38             1.0   
4                    2.7870                4.01            34.0   
...                     ...                 ...             ...   
449995               0.5789                0.19             4.0   
449996               1.9863                1.19            81.0   
449997               1.5944                1.61            28.0   
449998               2.8939                4.68            72.0   
449999               1.8925                0.09            30.0   

        delivered_orders  undelivered_orders  lifetime_order_count  \
0                   46.0                 0.0                 621.0   
1                    8.0                 0.0                 105.0   
2                    1.0                 0.0                  66.0   
3                    1.0                 0.0                 127.0   
4                   34.0                 0.0                  84.0   
...                  ...                 ...                   ...   
449995               4.0                 0.0                 127.0   
449996              81.0                 0.0                 105.0   
449997              28.0                 0.0                1488.0   
449998              72.0                 0.0                 105.0   
449999              30.0                 0.0                 108.0   

        session_time  hour-1  hour-2  hour-3  ...  hour-12  hour-13  hour-14  \
0                NaN       0       1       0  ...        0        0        0   
1           3.266667       0       1       0  ...        0        0        0   
2           9.816667       0       1       0  ...        0        0        0   
3          17.533333       0       1       0  ...        0        0        0   
4           1.350000       0       0       1  ...        0        0        0   
...              ...     ...     ...     ...  ...      ...      ...      ...   
449995    369.516667       0       0       0  ...        0        0        0   
449996    239.133333       0       0       0  ...        0        0        0   
449997    204.150000       0       0       0  ...        0        0        0   
449998     65.583333       0       0       0  ...        0        0        0   
449999    212.000000       0       0       0  ...        0        0        0   

        hour-15  hour-16  hour-17  hour-18  hour-19  hour-20  hour-21  
0             0        0        0        0        0        0        0  
1             0        0        0        0        0        0        0  
2             0        0        0        0        0        0        0  
3             0        0        0        0        0        0        0  
4             0        0        0        0        0        0        0  
...         ...      ...      ...      ...      ...      ...      ...  
449995        0        0        0        0        0        0        0  
449996        0        0        0        0        0        0        0  
449997        0        0        0        0        0        0        0  
449998        0        0        0        0        0        0        0  
449999        0        0        0        0        0        0        0  

[450000 rows x 28 columns]

In [16]:
import xgboost as xgb

In [48]:
regressor = xgb.XGBRegressor(
    n_estimators=100,
    reg_lambda=1,
    gamma=0,
    max_depth=4
)

In [49]:
regressor.fit(X_dum,Y)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
             gamma=0, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.300000012,
             max_delta_step=0, max_depth=4, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=100, n_jobs=12,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method='exact',
             validate_parameters=1, verbosity=None)

In [19]:
test=pd.read_csv("C:/Users/DELL/Projects/cascade-cup-22/test.csv")

In [20]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144844 entries, 0 to 144843
Data columns (total 16 columns):
 #   Column                Non-Null Count   Dtype  
---  ------                --------------   -----  
 0   order_time            144844 non-null  object 
 1   order_id              144844 non-null  int64  
 2   order_date            144844 non-null  object 
 3   allot_time            144844 non-null  object 
 4   accept_time           144776 non-null  object 
 5   rider_id              144844 non-null  int64  
 6   first_mile_distance   144844 non-null  float64
 7   last_mile_distance    144844 non-null  float64
 8   alloted_orders        140071 non-null  float64
 9   delivered_orders      139960 non-null  float64
 10  undelivered_orders    139960 non-null  float64
 11  lifetime_order_count  144066 non-null  float64
 12  reassignment_method   4632 non-null    object 
 13  reassignment_reason   4635 non-null    object 
 14  reassigned_order      4635 non-null    float64
 15  

In [21]:
test.drop(['reassignment_method','reassignment_reason','reassigned_order','order_date','allot_time'],axis=1,inplace=True)

In [22]:
test['order_time'] = pd.to_datetime(test.order_time, format='%Y-%m-%d %H:%M:%S')
test['hour']=test['order_time'].dt.hour

In [23]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144844 entries, 0 to 144843
Data columns (total 12 columns):
 #   Column                Non-Null Count   Dtype         
---  ------                --------------   -----         
 0   order_time            144844 non-null  datetime64[ns]
 1   order_id              144844 non-null  int64         
 2   accept_time           144776 non-null  object        
 3   rider_id              144844 non-null  int64         
 4   first_mile_distance   144844 non-null  float64       
 5   last_mile_distance    144844 non-null  float64       
 6   alloted_orders        140071 non-null  float64       
 7   delivered_orders      139960 non-null  float64       
 8   undelivered_orders    139960 non-null  float64       
 9   lifetime_order_count  144066 non-null  float64       
 10  session_time          139790 non-null  float64       
 11  hour                  144844 non-null  int64         
dtypes: datetime64[ns](1), float64(7), int64(3), object(1)
memo

In [24]:
odf=test['order_id']
test.drop(['order_time','order_id','accept_time','rider_id'],axis=1,inplace=True)


In [25]:
test['hour']=test['hour'].astype('category')
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144844 entries, 0 to 144843
Data columns (total 8 columns):
 #   Column                Non-Null Count   Dtype   
---  ------                --------------   -----   
 0   first_mile_distance   144844 non-null  float64 
 1   last_mile_distance    144844 non-null  float64 
 2   alloted_orders        140071 non-null  float64 
 3   delivered_orders      139960 non-null  float64 
 4   undelivered_orders    139960 non-null  float64 
 5   lifetime_order_count  144066 non-null  float64 
 6   session_time          139790 non-null  float64 
 7   hour                  144844 non-null  category
dtypes: category(1), float64(7)
memory usage: 7.9 MB


In [26]:
test_dum=pd.get_dummies(test,prefix_sep='-',drop_first=True)

In [27]:
test_dum.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144844 entries, 0 to 144843
Data columns (total 26 columns):
 #   Column                Non-Null Count   Dtype  
---  ------                --------------   -----  
 0   first_mile_distance   144844 non-null  float64
 1   last_mile_distance    144844 non-null  float64
 2   alloted_orders        140071 non-null  float64
 3   delivered_orders      139960 non-null  float64
 4   undelivered_orders    139960 non-null  float64
 5   lifetime_order_count  144066 non-null  float64
 6   session_time          139790 non-null  float64
 7   hour-2                144844 non-null  uint8  
 8   hour-3                144844 non-null  uint8  
 9   hour-4                144844 non-null  uint8  
 10  hour-5                144844 non-null  uint8  
 11  hour-6                144844 non-null  uint8  
 12  hour-7                144844 non-null  uint8  
 13  hour-8                144844 non-null  uint8  
 14  hour-9                144844 non-null  uint8  
 15  

In [28]:
test_dum['hour-21']=0


In [29]:
test_dum['hour-1']=0

In [30]:
y_pred = regressor.predict(test_dum)

In [31]:
y_pred

array([0.00624508, 0.01021784, 0.00238199, ..., 0.00558529, 0.01516906,
       0.00849732], dtype=float32)

In [32]:
sum=0
for i in y_pred:
    if i>=0.5:
        sum=sum+1

print(sum)

1126


In [33]:
y_pred[0]

0.006245076

In [34]:
for i in range(len(y_pred)):
    if y_pred[i]>=0.5:
        y_pred[i]=1
    elif y_pred[i]<0.5:
        y_pred[i]=0


In [35]:
y_pred

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [36]:
y_pred=pd.Series(y_pred)

In [37]:
y_pred=y_pred.astype(int)

In [38]:
y_pred

0         0
1         0
2         0
3         0
4         0
         ..
144839    0
144840    0
144841    0
144842    0
144843    0
Length: 144844, dtype: int32

In [39]:
my_sub=pd.DataFrame({'order_id':odf,'cancelled':y_pred})

In [40]:
my_sub

order_id  cancelled
0         130231          0
1         130232          0
2         130233          0
3         130234          0
4         130235          0
...          ...        ...
144839     41184          0
144840     41185          0
144841     41186          0
144842     41187          0
144843     41188          0

[144844 rows x 2 columns]

In [41]:
example=pd.read_csv("C:/Users/DELL/Projects/cascade-cup-22/sample_submission.csv")

In [42]:
example

order_id  cancelled
0         130231          0
1         130232          0
2         130233          0
3         130234          0
4         130235          0
...          ...        ...
144839     41184          0
144840     41185          0
144841     41186          0
144842     41187          0
144843     41188          0

[144844 rows x 2 columns]

In [43]:
my_sub.to_csv('sub.csv')

In [47]:
regressor_1 = xgb.XGBRegressor(
    max_depth=5,
    learning_rate=0.1
)

In [50]:
regressor_1.fit(X_dum,Y)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
             gamma=0, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.1, max_delta_step=0,
             max_depth=5, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=100, n_jobs=12,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method='exact',
             validate_parameters=1, verbosity=None)

In [55]:
y_pred_1 = regressor_1.predict(test_dum)

In [56]:
y_pred_1

array([0.00583235, 0.0109041 , 0.00296786, ..., 0.00628962, 0.00629561,
       0.00946227], dtype=float32)

In [57]:
sum=0
for i in y_pred_1:
    if i>=0.5:
        sum=sum+1

print(sum)

1098


In [63]:
for i in range(len(y_pred_1)):
    if y_pred_1[i]>=0.5:
        y_pred_1[i]=1
    elif y_pred_1[i]<0.5:
        y_pred_1[i]=0


In [64]:
y_pred_1

array([0, 0, 0, ..., 0, 0, 0])

In [67]:
y_pred_1=pd.Series(y_pred_1)
y_pred_1=y_pred_1.astype(int)

In [68]:
y_pred_1

0         0
1         0
2         0
3         0
4         0
         ..
144839    0
144840    0
144841    0
144842    0
144843    0
Length: 144844, dtype: int32

In [69]:
y_pred_1.unique()

array([0, 1])

In [70]:
y_pred_1.value_counts()

0    143746
1      1098
dtype: int64

In [71]:
my_sub_1=pd.DataFrame({'order_id':odf,'cancelled':y_pred_1})

In [72]:
my_sub_1.to_csv('sub_1.csv')

In [73]:
regressor_2 = xgb.XGBRegressor(
    max_depth=8,
    learning_rate=0.01
)

In [80]:
regressor_2.fit(X_dum,Y)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
             gamma=0, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.01, max_delta_step=0,
             max_depth=8, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=100, n_jobs=12,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method='exact',
             validate_parameters=1, verbosity=None)

In [81]:
y_pred_2 = regressor_2.predict(test_dum)

In [82]:
y_pred_2

array([0.18751243, 0.19061595, 0.18685654, ..., 0.18779399, 0.18865533,
       0.18954541], dtype=float32)

In [83]:
for i in range(len(y_pred_2)):
    if y_pred_2[i]>=0.5:
        y_pred_2[i]=1
    elif y_pred_2[i]<0.5:
        y_pred_2[i]=0


In [84]:
y_pred_2=pd.Series(y_pred_2)
y_pred_2=y_pred_2.astype(int)

In [85]:
y_pred_2.value_counts()

0    143700
1      1144
dtype: int64

In [86]:
my_sub_2=pd.DataFrame({'order_id':odf,'cancelled':y_pred_2})

In [87]:
my_sub_2.to_csv('sub_2.csv')

In [89]:
example['cancelled'].unique()

array([0], dtype=int64)

In [90]:
regressor_3 = xgb.XGBRegressor(
    max_depth=6,
    learning_rate=0.05
)

In [92]:
regressor_3.fit(X_dum,Y)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
             gamma=0, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.05, max_delta_step=0,
             max_depth=6, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=100, n_jobs=12,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method='exact',
             validate_parameters=1, verbosity=None)

In [93]:
y_pred_3 = regressor_3.predict(test_dum)

In [94]:
y_pred_3

array([0.00880539, 0.0140007 , 0.00698292, ..., 0.01512781, 0.01379051,
       0.01186159], dtype=float32)

In [95]:
for i in range(len(y_pred_3)):
    if y_pred_3[i]>=0.5:
        y_pred_3[i]=1
    elif y_pred_3[i]<0.5:
        y_pred_3[i]=0

In [97]:
y_pred_3=pd.Series(y_pred_3)
y_pred_3=y_pred_3.astype(int)

In [99]:
y_pred_3.value_counts()

0    143725
1      1119
dtype: int64

In [100]:
my_sub_3=pd.DataFrame({'order_id':odf,'cancelled':y_pred_3})

In [101]:
my_sub_3

order_id  cancelled
0         130231          0
1         130232          0
2         130233          0
3         130234          0
4         130235          0
...          ...        ...
144839     41184          0
144840     41185          0
144841     41186          0
144842     41187          0
144843     41188          0

[144844 rows x 2 columns]

In [102]:
my_sub_3.to_csv('sub_3.csv')